import asphaltBall1 from "./asphalt.jpg";
import grassBall1 from "./grass.jpg";
import footyBall1 from "./footyvolley.jpg";
import volleyBall1 from "./volleyball.jpg";
import basketBall1 from "./basketball.jpg";
import logo1 from "./logo.jpg";
import basketGame1 from "./basketgame.jpg";
import futsalGame1 from "./Futsalgame.jpg";
import footyGame1 from "./footyvolleygame.jpg";
import volleyGame1 from "./volleyBallGame.jpg";
import soccerGame1 from "./soccerGame.jpg";
import profile1 from "./profile.jpg";

export const profile = profile1;
export const basketGame = basketGame1;
export const futsalGame = futsalGame1;
export const footyGame = footyGame1;
export const volleyGame = volleyGame1;
export const soccerGame = soccerGame1;
export const logo = logo1;
export const basketBall = basketBall1;
export const asphaltBall = asphaltBall1;
export const footyBall = footyBall1;
export const volleyBall = volleyBall1;
export const grassBall = grassBall1;